package com.app.enums;

public enum SpecialityType {
	DERMATOLOGISTS, CARDIOLOGISTS, GENERAL_PHYSICIAN, UROLOGISTS, NEUROLOGISTS, RHEUMATOLOGISTS, RADIOLOGISTS,
	PULMONOLOGISTS, PSYCHIATRISTS, PODIATRISTS, PHYSIATRISTS, PEDIATRICIANS, PATHOLOGIST, OTOLARYNGOLOGISTS, OSTEOPATHS,
	OPHTHALMOLOGISTS, ONCOLOGISTS, GYNECOLOGISTS, NEPHROLOGISTS, INTERNISTS, HEMATOLOGISTS, GASTROENTEROLOGISTS,
	ENDOCRINOLOGISTS, ANESTHESIOLOGISTS, IMMUNOLOGISTS

}
